version: '3.8'
services:
  db:
    container_name: ToDoManager_bd
    image: postgres:14.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT:-5432}:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $DB_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      back_nw:
  api:
    container_name: ToDoManager_api
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
        back_nw:
  front:
    container_name: ToDoManager_front
    image: sermalenk/skypro-front:lesson-34
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_started
    networks:
      front_nw:
volumes:
  postgres_data:
networks:
  back_nw:
    driver: bridge
  front_nw:
    driver: bridge